print("Hello! Answer the following questions to create a band name.")
city_name = input("What city did you grow up in?\n")
pet_name = input("What is the name of your pet?\n")
band_name = (city_name) + " " + (pet_name)
print("Your band name is " + band_name ) 
